{% set name = "perl-extutils-cppguess" %}
{% set version = "0.23" %}
{% set sha256 = "f96c48984eb6d8efb7d933b34f361d0c8b38335e3e5382e9aeccc0aa519a002c" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/E/ET/ETJ/ExtUtils-CppGuess-0.23.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('cxx') }}

  host:
    - perl
    - perl-data-dumper
    - perl-extutils-makemaker
    - perl-module-build
    - perl-extutils-manifest
    - perl-capture-tiny

  run:
    - perl
    - perl-capture-tiny

test:
  imports:
    - ExtUtils::CppGuess

about:
  home: http://metacpan.org/pod/ExtUtils::CppGuess
  license: perl_5
  summary: 'guess C++ compiler and flags'
