{% set name = "knock-knock" %}
{% set version = "0.3.8" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://files.pythonhosted.org/packages/86/ca/3fe0b1b8ddf9fa992cd7eb2e2141bbb9d4e16db4b5e5903842c8f24c0ed1/knock_knock-0.3.8.tar.gz"
  sha256: "151144a0e5e83c30d0c81f6dbb32ce85a39fd3b01b198afedee10c6b017aa639"

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - biopython >=1.70
    - blast ==2.7.1
    - bokeh >=0.12.14
    - hits >=0.1
    - ipywidgets >=7.1.2
    - matplotlib-base >=2.1.2
    - minimap2 ==2.16
    - nbconvert >=5.3.1
    - nbformat >=4.4.0
    - numpy >=1.14.2
    - pandas >=0.22.0
    - parallel >=20190522
    - pillow >=5.0.0
    - pysam >=0.14
    - python >=3.6
    - pyyaml >=3.12
    - samtools >=1.9
    - star >=2.7.1
    - tqdm >=4.31.1

test:
  imports:
    - knock_knock
  commands:
    - knock-knock -h
    - blastn -version
    - minimap2 --version
    - samtools --version
    - STAR --version


about:
  home: "https://github.com/jeffhussmann/knock-knock"
  license: "GPL-3"
  summary: "toolkit for analyzing CRISPR knock-in experiments"

extra:
  recipe-maintainers:
    - jeffhussmann
