{% set version = "1.1.1" %}
{% set sha256 = "90f5d33f2fa530ec5aa05a1d6756231cf978adef53e7bf1716214a27eb56f008" %}

package:
  name: bigscape
  version: {{ version }}

source:
  url: https://git.wageningenur.nl/medema-group/BiG-SCAPE/-/archive/v{{ version }}/BiG-SCAPE-v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python

requirements:
  host:
    - python ==3.6
  run:
    - python ==3.6
    - hmmer
    - biopython
    - fasttree
    - numpy
    - scipy
    - networkx
    - scikit-learn ==0.19.1

test:
  commands:
    - 'python bigscape.py --version'

about:
  home: https://git.wageningenur.nl/medema-group/BiG-SCAPE
  license: GNU Affero v3
  summary: Biosynthetic Genes Similarity Clustering and Prospecting Engine.
