{% set version = "0.2.0" %}
{% set github = "https://github.com/acidgenomics/r-acidsinglecell" %}

package:
  name: r-acidsinglecell
  version: "{{ version }}"

source:
  url: "{{ github }}/archive/v{{ version }}.tar.gz"
  sha256: 8cd1903736527f85d3968e1a4a8f8f2a17d071493fac259d39ad90670a5064ae

build:
  number: 0
  noarch: generic

requirements:
  host:
    # Depends:
    - r-base
    # Imports:
    - bioconductor-singlecellexperiment >=1.14.0
    - r-acidbase >=0.4.3
    - r-acidcli >=0.1.5
    - r-acidexperiment >=0.2.0
    - r-acidgenerics >=0.5.19
    - r-acidplyr >=0.1.20
    - r-goalie >=0.5.4
    - r-pipette >=0.7.0
    - r-scales >=1.1.1
    - r-stringr >=1.4.0
    - r-syntactic >=0.5.0
  run:
    # Depends:
    - r-base
    # Imports:
    - bioconductor-singlecellexperiment >=1.14.0
    - r-acidbase >=0.4.3
    - r-acidcli >=0.1.5
    - r-acidexperiment >=0.2.0
    - r-acidgenerics >=0.5.19
    - r-acidplyr >=0.1.20
    - r-goalie >=0.5.4
    - r-pipette >=0.7.0
    - r-scales >=1.1.1
    - r-stringr >=1.4.0
    - r-syntactic >=0.5.0

test:
  commands:
    - $R -e "library('AcidSingleCell')"

about:
  home: https://r.acidgenomics.com/packages/acidsinglecell/
  dev_url: "{{ github }}"
  license: AGPL-3.0
  license_file: LICENSE
  license_family: GPL
  summary: Toolkit for single-cell RNA-seq analysis that extends the
    functionality of SingleCellExperiment.

extra:
  recipe-maintainers:
    - acidgenomics
    - mjsteinbaugh
