{% set version = "" %}
{% set sha256 = "" %}

package:
  name: rrefinder
  version: {{ version }}

source:
  url: https://github.com/Alexamk/RREFinder/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed . -vv"

requirements:
  host:
    - python
  run:
    - _libgcc_mutex
    - _openmp_mutex
    - biopython >=1.76
    - blast-legacy
    - ca-certificates
    - certifi
    - hmmer >=3.3
    - libblas
    - libcblas
    - libffi
    - libgcc-ng
    - libgfortran-ng
    - libgomp
    - liblapack
    - libopenblas
    - libstdcxx-ng
    - ncurses
    - numpy
    - openssl
    - pip
    - psipred >=4.01
    - python
    - python_abi
    - readline
    - setuptools
    - sqlite
    - tk
    - wheel
    - xz
    - zlib

test:
  commands:
    - 'python RRE.py --version'

about:
  home: https://github.com/Alexamk/RREFinder
  #license:
  summary: Bioinformatic application for the detection of RREs in protein sequences of interest
