{% set version = "0.15.0" %}
{% set github = "https://github.com/acidgenomics/r-basejump" %}

package:
  name: r-basejump
  version: "{{ version }}"

source:
  url: "{{ github }}/archive/v{{ version }}.tar.gz"
  sha256: ddd9d4da958bcb70b8bd96d7246949422a4bf372f24ea4e558c5e6a2d375ff3f

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    # Depends:
    - r-base
    # Imports:
    - r-acidbase >=0.4.5
    - r-acidcli >=0.1.6
    - r-acidexperiment >=0.2.1
    - r-acidgenerics >=0.5.20
    - r-acidgenomes >=0.2.18
    - r-acidmarkdown >=0.1.3
    - r-acidplyr >=0.1.22
    - r-acidsinglecell >=0.1.8
    - r-pipette >=0.7.1
    - r-stringr >=1.4.0
    - r-syntactic >=0.5.0
  run:
    # Depends:
    - r-base
    # Imports:
    - r-acidbase >=0.4.5
    - r-acidcli >=0.1.6
    - r-acidexperiment >=0.2.1
    - r-acidgenerics >=0.5.20
    - r-acidgenomes >=0.2.18
    - r-acidmarkdown >=0.1.3
    - r-acidplyr >=0.1.22
    - r-acidsinglecell >=0.1.8
    - r-pipette >=0.7.1
    - r-stringr >=1.4.0
    - r-syntactic >=0.5.0

test:
  commands:
    - $R -e "library('basejump')"

about:
  home: https://r.acidgenomics.com/packages/basejump/
  dev_url: "{{ github }}"
  license: AGPL-3.0
  license_file: LICENSE
  license_family: GPL
  summary: Base functions for bioinformatics and R package development.

extra:
  recipe-maintainers:
    - acidgenomics
    - mjsteinbaugh
