{% set name = "mavenn" %}
{% set version = "1.0.1" %}

package:
  name: mavenn
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: b9279db8b75b43e0ada6f1a76a5cdb846f090527c5244068b8311d002b2aa4b1

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv --ignore-installed --no-deps"

requirements:
  host:
    - pip
    - python >=3
  run:
    - logomaker >=0.8
    - matplotlib-base >=3.2.0
    - numpy
    - pandas >=1.1.2
    - python >=3
    - scikit-learn >=0.22
    - tensorflow >=2.3.0

test:
  imports:
    - sklearn
    - mavenn

about:
  home: "http://mavenn.readthedocs.io"
  license: MIT
  license_family: MIT
  summary: "MAVE-NN: genotype-phenotype maps from multiplex assays of variant effect"
  dev_url: "http://github.com/jbkinney/mavenn"

extra:
  recipe-maintainers:
    - andrefaure
