{% set version = "0.5.0" %}
{% set github = "https://github.com/acidgenomics/r-acidbase" %}

package:
  name: r-acidbase
  version: "{{ version }}"

source:
  url: "{{ github }}/archive/v{{ version }}.tar.gz"
  sha256: 4080484e4177c2ca1c871392ccd4f071ce4938dbdc55cc6e9ea310cf6200e950
  
build:
  number: 0
  noarch: generic

requirements:
  host:
    # Depends:
    - r-base
    # Imports:
    - r-acidcli >=0.1.6
    - r-acidgenerics >=0.5.20
    - r-goalie >=0.5.4
    - r-processx >=3.5.2
  run:
    # Depends:
    - r-base
    # Imports:
    - r-acidcli >=0.1.6
    - r-acidgenerics >=0.5.20
    - r-goalie >=0.5.4
    - r-processx >=3.5.2

test:
  commands:
    - $R -e "library('AcidBase')"

about:
  home: https://r.acidgenomics.com/packages/acidbase/
  dev_url: "{{ github }}"
  license: AGPL-3.0
  license_file: LICENSE
  license_family: GPL
  summary: Low-level base functions imported by Acid Genomics packages.

extra:
  recipe-maintainers:
    - acidgenomics
    - mjsteinbaugh
