{% set name = "pgcgap" %}
{% set version = "1.0.33" %}

package:
  name: '{{ name }}'
  version: '{{ version }}'

source:
  url: https://github.com/liaochenlanruo/pgcgap/archive/v{{ version }}.tar.gz
  sha256: 7d1cfc96d306fcff152e6f480e5dbdab707f2d07ab51b0f6a265d785e3e0b70d


build:
  number: 0
  noarch: generic

requirements:
  host:
    - perl
    - perl-bioperl =1.7.2
    - perl-file-tee =0.07
#    - perl-sys-info
    - perl-file-copy-recursive =0.45
  run:
    - abricate =1.0.1
    - canu =2.0
    - openjdk =8.0.152
    - abyss =2.2.5
    - prokka =1.14.6
    - mash =2.2.2
    - roary =3.13.0
    - orthofinder =2.3.8
#    - gubbins =2.4.1
#    - iqtree
#    - minced
#    - fastme >=2.1.5
    - fastani =1.32
    - fastp =0.20.1
#    - fasttree
    - pal2nal =14.1
    - perl
    - perl-file-tee =0.07
    - perl-data-dumper =2.173
    - perl-pod-usage =1.69
#    - perl-getopt-long >=2.50
    - perl-parallel-forkmanager =2.02
    - perl-file-copy-recursive =0.45
    - perl-posix =1.38
#    - perl-sys-info
    - htslib =1.10.2
    - snippy =4.6.0
    - sickle-trim >=1.33
    - r-base =3.6.3
    - r-ggplot2 =3.3.3
    - r-gplots =3.1.1
    - r-corrplot =0.88
    - trimal =1.4.1
    - python =3.7.8
    - matplotlib-base =3.4.1
    - seaborn =0.11.1
    - numpy =1.20.2
    - pandas =1.2.3
    - biopython =1.78
    - r-pheatmap =1.0.12
    - r-plotrix =3.8_1
    - unicycler =0.4.7
    - wget =1.20.1
    - coreutils =8.31
    - mamba

test:
  commands:
    - pgcgap --version

about:
  home: https://github.com/liaochenlanruo/pgcgap/blob/master/README.md
  license: GPLv3
  license_family: GPL
  license_file: LICENSE
  summary: A prokaryotic genomics and comparative genomics analysis pipeline
  description: PGCGAP is a pipeline for prokaryotic comparative genomics analysis. It can take the pair-end reads, ONT reads or PacBio reads as input. In addition to genome assembly, gene prediction and annotation, it can also get common comparative genomics analysis results such as phylogenetic trees of single-core proteins and core SNPs, pan-genome, whole-genome Average Nucleotide Identity (ANI), orthogroups and orthologs, COG annotations, substitutions (SNPs) and insertions/deletions (indels), and antimicrobial and virulence genes mining with only one line of commands.
  dev_url: https://github.com/liaochenlanruo/pgcgap/tree/master

extra:
  identifiers:
    - biotools:pgcgap
  recipe-maintainers:
    - liaochenlanruo
  doi:
    - 10.21203/rs.2.21224/v6
