{% set version = "0.5.1" %}
{% set github = "https://github.com/acidgenomics/r-syntactic" %} 

package:
  name: r-syntactic
  version: "{{ version }}"

source:
  url: "{{ github }}/archive/v{{ version }}.tar.gz"
  sha256: 4933fe59d7c5566d47c295c2f797787dc8c09e0c43d9486fed9f90cdb25761fb

build:
  noarch: generic
  number: 0

requirements:
  host:
      # Depends:
    - r-base
      # Imports:
    - r-acidbase >=0.4.3
    - r-acidcli >=0.1.5
    - r-acidgenerics >=0.5.19
    - r-goalie >=0.5.4
    - r-stringi >=1.7.3
    - r-stringr >=1.4.0
  run:
      # Depends:
    - r-base
      # Imports:
    - r-acidbase >=0.4.3
    - r-acidcli >=0.1.5
    - r-acidgenerics >=0.5.19
    - r-goalie >=0.5.4
    - r-stringi >=1.7.3
    - r-stringr >=1.4.0

test:
  commands:
    - $R -e "library('syntactic')"

about:
  home: https://r.acidgenomics.com/packages/syntactic/
  dev_url: "{{ github }}"
  license: AGPL-3
  license_file: LICENSE
  license_family: GPL
  summary: Make syntactically valid names out of character vectors.

extra:
  recipe-maintainers:
    - acidgenomics
    - mjsteinbaugh
